@echo off
echo Starting Social Media Platform...
echo Starting Backend (Port 5000)...
start "Backend Server" cmd /k "cd backend && npm run dev"
echo Starting Frontend (Port 3000)...
start "Frontend Server" cmd /k "cd frontend && npm run dev"
echo Done! Please visit http://localhost:3000
